# Generated by Django 4.1.1 on 2022-09-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ricetta", name="costo", field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="ricetta",
            name="portata",
            field=models.CharField(default="primo", max_length=50),
        ),
        migrations.AddField(
            model_name="ricetta",
            name="regime_alimentare",
            field=models.CharField(default="veg", max_length=50),
        ),
    ]
