# Generated by Django 4.1.1 on 2022-09-22 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestione", "0003_alter_ricetta_options_ricetta_porzioni_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ricetta",
            name="utente",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="non_so_cosa_vada",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
