# Generated by Django 4.1.1 on 2022-09-23 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestione", "0005_alter_ricetta_utente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ricetta",
            name="utente",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="non_so_cosa_vada",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
