# Generated by Django 4.1.1 on 2022-09-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0008_ingredient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient", old_name="recipe", new_name="ricetta",
        ),
    ]
