# Generated by Django 4.1.1 on 2022-09-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0009_rename_recipe_ingredient_ricetta"),
    ]

    operations = [
        migrations.AddField(
            model_name="ricetta",
            name="immagine",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
