# Generated by Django 4.1.1 on 2022-09-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0010_ricetta_immagine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ricetta",
            name="difficoltá",
            field=models.CharField(
                choices=[("1", "Bassa"), ("2", "Media"), ("3", "Alta")], max_length=50
            ),
        ),
    ]
