# Generated by Django 4.1.1 on 2022-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0011_alter_ricetta_difficoltá"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="unita_di_misura",
            field=models.CharField(
                choices=[("1", "grammi"), ("2", "unitá"), ("3", "ml")],
                default="grammi",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ricetta",
            name="difficoltá",
            field=models.CharField(
                choices=[("1", "Bassa"), ("2", "Media"), ("3", "Alta")],
                default="Bassa",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ricetta",
            name="portata",
            field=models.CharField(
                choices=[
                    ("1", "Antipasto"),
                    ("2", "Primo"),
                    ("3", "Secondo"),
                    ("4", "Dolce"),
                ],
                default="Primo",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="ricetta",
            name="regime_alimentare",
            field=models.CharField(
                choices=[("1", "Vegetariano"), ("2", "Vegano"), ("3", "Nessuno")],
                default="Nessuno",
                max_length=50,
            ),
        ),
    ]
