# Generated by Django 4.1.1 on 2022-09-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestione",
            "0012_ingredient_unita_di_misura_alter_ricetta_difficoltá_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="ricetta", name="regime_alimentare",),
        migrations.AddField(
            model_name="ricetta",
            name="gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ricetta",
            name="vegano",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ricetta",
            name="vegetariano",
            field=models.BooleanField(default=False),
        ),
    ]
