# Generated by Django 4.1.1 on 2022-09-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestione",
            "0013_remove_ricetta_regime_alimentare_ricetta_gluten_free_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="nome",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="quantitá",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unita_di_misura",
            field=models.CharField(
                choices=[("1", "grammi"), ("2", "unitá"), ("3", "ml")],
                default="grammi",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ricetta", name="costo", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ricetta", name="porzioni", field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ricetta",
            name="tempo_cottura",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ricetta",
            name="tempo_preparazione",
            field=models.IntegerField(default=0),
        ),
    ]
