# Generated by Django 4.1.1 on 2022-09-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0014_alter_ingredient_nome_alter_ingredient_quantitá_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="unita_di_misura",
            field=models.CharField(
                choices=[(1, "grammi"), ("2", "unitá"), ("3", "ml")],
                default="grammi",
                max_length=50,
            ),
        ),
    ]
