# Generated by Django 4.1.1 on 2022-09-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0015_alter_ingredient_unita_di_misura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="nome",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="quantitá",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="unita_di_misura",
            field=models.CharField(
                choices=[("1", "grammi"), ("2", "unitá"), ("3", "ml")],
                default="grammi",
                max_length=50,
            ),
        ),
    ]
