# Generated by Django 4.1.1 on 2022-09-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0016_alter_ingredient_nome_alter_ingredient_quantitá_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="nome",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="quantitá",
            field=models.IntegerField(null=True),
        ),
    ]
