# Generated by Django 4.1.1 on 2022-09-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0017_alter_ingredient_nome_alter_ingredient_quantitá"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient", name="nome", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="ingredient", name="quantitá", field=models.IntegerField(),
        ),
    ]
