# Generated by Django 4.1.1 on 2022-09-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0021_alter_ingredient_nome_alter_ingredient_quantitá"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="nome",
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="quantitá",
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
