# Generated by Django 4.1.1 on 2022-09-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0023_alter_ingredient_nome_alter_ingredient_quantitá"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ricetta",
            name="immagine",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
