# Generated by Django 4.1.1 on 2022-09-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0025_alter_ingredient_nome_alter_ricetta_immagine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="quantitá",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
