# Generated by Django 4.1.1 on 2022-10-01 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestione", "0026_alter_ingredient_quantitá"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ricetta",
            name="utente",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Recensione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "punteggio",
                    models.IntegerField(
                        choices=[("1", 1), ("2", 2), ("3", 3), ("4", 4), ("5", 5)],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "ricetta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestione.ricetta",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Recensione",},
        ),
    ]
