# Generated by Django 4.1.1 on 2022-10-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0027_alter_ricetta_utente_recensione"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recensione",
            name="ricetta",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestione.ricetta",
            ),
        ),
    ]
