# Generated by Django 4.1.1 on 2022-10-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0028_alter_recensione_ricetta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recensione",
            name="punteggio",
            field=models.IntegerField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                default=None,
                null=True,
            ),
        ),
    ]
