# Generated by Django 4.1.1 on 2022-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0030_alter_recensione_punteggio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recensione",
            name="punteggio",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
