# Generated by Django 4.1.1 on 2022-10-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0034_alter_recensione_punteggio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recensione",
            name="punteggio",
            field=models.IntegerField(
                choices=[(0, "i"), (1, "i"), (2, "i"), (3, "i"), (4, "i")], default="1"
            ),
        ),
    ]
