# Generated by Django 4.1.1 on 2022-10-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestione", "0038_alter_recensione_punteggio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recensione", options={"verbose_name_plural": "Recensioni"},
        ),
    ]
