# Generated by Django 4.1.1 on 2022-10-02 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestione", "0040_alter_recensione_punteggio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recensione",
            name="punteggio",
            field=models.IntegerField(
                choices=[(0, "-"), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default="-"
            ),
        ),
        migrations.CreateModel(
            name="RicettePreferite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ricetta",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestione.ricetta",
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
