# Generated by Django 4.1.2 on 2022-10-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0042_alter_ricetta_difficoltá'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricetta',
            name='procedimento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
