# Generated by Django 4.1.2 on 2022-10-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0043_ricetta_procedimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unita_di_misura',
            field=models.CharField(choices=[('grammi', 'grammi'), ('unitá', 'unitá'), ('ml', 'ml')], default='grammi', max_length=50),
        ),
    ]
